# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 06:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fee Amount')),
                ('is_installments_allowed', models.BooleanField(default=False, verbose_name='Is student allowed to submit fee in installments')),
                ('number_of_installments', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Installments')),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Installment Number')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Installment Amount')),
                ('deadline', models.DateTimeField()),
                ('course_fee_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_fee_installments', to='fee.CourseFeeDetail')),
            ],
        ),
    ]
