# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 06:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('student_list', django.contrib.postgres.fields.jsonb.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_counselling', to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[(b'2010', '2010-2011'), (b'2011', '2011-2012'), (b'2012', '2012-2013'), (b'2013', '2013-2014'), (b'2014', '2014-2015'), (b'2015', '2015-2016'), (b'2016', '2016-2017'), (b'2017', '2017-2018'), (b'2018', '2018-2019'), (b'2019', '2019-2020'), (b'2020', '2020-2021'), (b'2021', '2021-2022'), (b'2022', '2022-2023'), (b'2023', '2023-2024')], max_length=15, verbose_name='Session')),
                ('is_admission_still_open', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCounsellingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Choice')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_choosed_by', to='main.Branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_choices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
