# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 16:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('number_of_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Number of rooms ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostelRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of rooms')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Room Number')),
                ('allotment', models.ManyToManyField(related_name='rooms_student', to=settings.AUTH_USER_MODEL)),
                ('hostel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='hostel.HostelRooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity of room')),
                ('minimun_seniority_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimun Seniority Required')),
                ('preference', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5, verbose_name='Preference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hostelrooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='hostel.RoomType'),
        ),
    ]
